### ISSUE TITLE
week 01 回覆

### ISSUE THREAD

**Issue by azole** [neopan0000718/git-practice#1]
- 之後的作業，除了專有名詞外，請你用中文撰寫，除非你很有把握你的英文寫得很好，能精確表達你想要表達的東西。(以這次繳交的內容來說，我不確定是你原本就是想要呈現這個程度的內容，還是因為被英文能力給影響了）
- git.md 
  - `When you create a new branch, Git makes a copy of the current branch pointer (the commit you're currently on) and gives it a new name.` 你這裡的 copy，具體的意思是指？（例如到底複製了什麼東西？有沒有實際觀察到的例子來佐證這句話？）
  - Q2 你做了一些觀察跟比較，這邊做得不錯，但是在呈現上，你希望看的人看到什麼？截圖通常是用來輔佐的，你可以透過文字描述＋對圖片做特別標註，來讓閱讀的人更具體地知道你要想呈現什麼。
  - 你在 Q1 跟 Q3 中用到的圖片與截圖，應該是來自網路上的資料？如果要這樣全文引用，記得要註明出處。

**Comment by YCNeo** [comment]
1. 好的，之後會注意
2.1 檢查後發現copy是寫錯的，正確是 create a new pointer point to the current commit and give it a new name.
2.2 了解，之後作業若有附圖，會額外加上方框或圓圈來凸顯該圖片的主題
2.3 好的，下次會注意

**Comment by azole** [comment]
謝謝你的回覆，記得持續改善！

如果沒有其他要跟我討論的部分，這個 issue 可以 close 了。
